### ISSUE TITLE
Already Made a video for 'Game'. Re-checking in 1 hour. ERROR

### ISSUE THREAD

**Issue by NinuzIBZ** [offish/twitchtube#11]
The problem is quite simple.
No matter if the script generated a video in the last 24 hours, but it seems to only work one time.
Also, on the config you can check the time the script check if a video have been made but the 1 hour message is hard coded.
So it not show the currently time set in the config.

Basically it works only one day.
I wasnt able to let the script generate 2 clips from 2 differents days.

**Comment by offish** [comment]
The bot was originally meant to only make 1 video for each game once a day. It doesn't actually check if it has made a video or downloaded any clips. It will only see if there exists a folder with the current date as folder name, if this folder exists, it think there has been made a video for today. I'll try to fix this when I have the time, and add some more customization.
