### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Laezor** [offish/twitchtube#15]
![image](https://user-images.githubusercontent.com/32393101/102674663-6da3f800-419f-11eb-99b9-f64fbff149c7.png)

**Comment by Gobot1234** [comment]
Traceback doesn't match that error and `setcheckinterval` doesn't appear to be used anywhere in twitchtube

**Comment by Laezor** [comment]
Yeah I tried to search setcheckinterval. I don't know why but I am getting this error when it tries to combine the clips.
