### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jozz024** [offish/twitchtube#27]
Add a section to provide a Thumbnail?

**Comment by offish** [comment]
I might add this. It's already supported in the package I'm going to implement. Won't add automatic thumbnail generation though, but will look into specifying a "static" one in the config file, like descriptions or titles work now.

**Comment by jozz024** [comment]
ah yea that'll work great, would it just be a filepath then?

**Comment by offish** [comment]
Yep

**Comment by jozz024** [comment]
Nice, i'll close the issue then.
