### ISSUE TITLE
Add support for Counter-Strike: Global Offensive

### ISSUE THREAD

**Issue by genjikowa** [offish/twitchtube#28]
I want to use this for global offensive counter strike, still can't use it? I could make a video tutorial to use the software. Thank you.

**Comment by jozz024** [comment]
that isn't the issue iirc, the issue is that the game is Counter Strike: Global Offensive, and that : messes things up

**Comment by offish** [comment]
I'll try to fix this and add the thumbnail stuff tomorrow.

**Comment by genjikowa** [comment]
First of all thank you very much for responding so quickly !!
I would like to know if you could make a video tutorial to know how to install and operate the software?
I don't really understand programming codes.
Sorry it is a lot of work for you but I am really very interested in this project.
Counter Strike is one of my favorite games and I want to make compilations with this game.
Greetings.

**Comment by offish** [comment]
If you read through the whole README and follow every step, it should be quite easy to setup, even if you don't know anything about programming. If you still need help, you can just send a message in the Discord server by clicking the Discord badge/picture, and I'll try to help you out.

**Comment by genjikowa** [comment]
I have updated my previous comment I do not know if you have been able to read it again.
Where is the Discord server? 
i don't see the image

**Comment by offish** [comment]
You can the Discord here https://discord.com/invite/t8nHSvA or by looking at the top row of images in the README.

To your edits:
1. Yes it's possible to add a graphical interface, but I will not implement that. If anyone else would do the work, I would merge. It's intended to be a simple small program that gets the most viewed clips, and make a compilation of them. Only reason would be to select or deselect clips I guess, which is something I personally don't really care much about.

2. I don't really get what you're asking for here, but the program downloads X amount of clips depending on specified `VIDEO_LENGTH`. It then tries to get all the clips which has been downloaded and add this into a compilation. So it doesn't really select the "best" ones, just the most viewed ones.
