### ISSUE TITLE
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escap

### ISSUE THREAD

**Issue by matorina22** [offish/twitchtube#30]
After running the python main.py command I get this error.

Traceback (most recent call last):
  File "C:\Users\****\Downloads\youtube\twitchtube-master\main.py", line 8, in <module>
    from twitchtube.config import *
  File "C:\Users\****\Downloads\youtube\twitchtube-master\twitchtube\config.py", line 15
    ROOT_PROFILE_PATH = "C:\Users\****\AppData\Roaming\Mozilla\Firefox\Profiles\5q8sjx41.Selenium2"
                                                                                                  ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by Gobot1234** [comment]
put an r infront of the string

**Comment by matorina22** [comment]
Doesn't work I don't even know what you mean by that

**Comment by matorina22** [comment]
Think it worked man thanks!

**Comment by execptionerror** [comment]
Already Solved [SyntaxError: (unicode error) ‘unicodeescape’ codec can’t decode bytes in position 2-3: truncated \UXXXXXXXX escape](https://flutterq.com/syntaxerror-unicode-error-unicodeescape-codec-cant-decode-bytes-in-position-2-3-trunca/)
