### ISSUE TITLE
only uploads one clip and then says already made a video for "channel"

### ISSUE THREAD

**Issue by critiqalfish** [offish/twitchtube#33]
i constantly have to rerun the script to get it to work

**Comment by offish** [comment]
Could you provide some more information? Does it render a video, but the video contains only 1 clip? What channel and period are you trying to get clips from? It's made to only make 1 video for each channel or game a day, it checks if a rendered.mp4 file exists under the current date and category. What do you mean by "get it to work"?

**Comment by critiqalfish** [comment]
Oh ok i didnt knew it was made to only make 1 clip per day but everything else works fine :)
