### ISSUE TITLE
Error when trying to upload: Unable to locate element: .../ytcp-mention-textbox[2]

### ISSUE THREAD

**Issue by gantoin** [offish/twitchtube#34]
Hi ! I tried to upload a video today but there is this error :
```
twitchtube | 19:36:09 - error: There was an error Message: Unable to locate element: /html/body/ytcp-uploads-dialog/paper-dialog/div/ytcp-animatable[1]/ytcp-uploads-details/div/ytcp-uploads-basics/ytcp-mention-textbox[2]
 when trying to upload to YouTube
```
Am I the only one who can't upload recently with twitchtube?
Maybe there was an update of Youtube upload page ? Idk, I will fork and check what's wrong.

**Comment by offish** [comment]
Should be able to fix this issue by updating the opplast package `pip install --upgrade opplast`. 
Seems like YouTube have changed around on a couple of things, so it might not work. Works more times than not, but still some videos that just says "Uploading..." on YouTube and nothing ever happens.

**Comment by gantoin** [comment]
Fixed with `pip install --upgrade opplast` ; it works! Thanks
