### ISSUE TITLE
[Feature Request] mix clip when in channel mode

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [offish/twitchtube#35]
Hi, i love your python app 👍 
I was thinking that it would be a great addition to do like the game mode but for the channel mode 👍 and maybe the name of the streamers in simple text at the start of any clip 👍

**Comment by offish** [comment]
I don't really understand exactly what you mean. Do you want to get clips from a specific game and specific channel? E.g. only "xQcOW" clips with "Just Chatting" as game? This is not supported by the Twitch API endpoint I'm using, and I don't really want to make a workaround to add this. 
I feel like adding the name of a streamer on the start of each clip, is too "specific" for this program. I might add a little note with the streamer name in the corner, or something similar to that on a later date.

**Comment by TomAvecLeVdsl** [comment]
No actualy i would love to have clips from 5 diferent streamers in only 1 mixed video file ready for youtube, like mixing diferent streamers clips to aproximately the same ratio to have a completed video 👍

**Comment by offish** [comment]
Oh okay, I'll try to add that.

**Comment by TomAvecLeVdsl** [comment]
Awsome 👍 i'l keep an eye for updates :)
