### ISSUE TITLE
how we can modify it so that it add all the clips of the day and not just the top clips, thank you

### ISSUE THREAD

**Issue by Mehdi94i** [offish/twitchtube#36]
how we can modify it so that it add all the clips of the day and not just the top clips, thank you

**Comment by offish** [comment]
The maximum amount of clips it can get is 100. To make it use all the 100 clips, set `VIDEO_LENGTH` to some big value.

**Comment by Mehdi94i** [comment]
I can't make an 8 minute video, always 2 minute maximum video.
french video?

**Comment by Mehdi94i** [comment]
he gets 3 to 5 video maximum

**Comment by offish** [comment]
What game/channel and language are you getting?

**Comment by Mehdi94i** [comment]
all the games in French language, but when I switch to English it works

**Comment by offish** [comment]
You can check how many clips that exists by going to https://www.twitch.tv/directory/game/Just%20Chatting/clips?range=24hr and setting the language to the one you want to use. You can also change the range to be weekly or monthly.

**Comment by Mehdi94i** [comment]
thank you
