### ISSUE TITLE
Freeze of my computer

### ISSUE THREAD

**Issue by maxencefiu** [offish/twitchtube#39]
Hello,
It seems to me to have configured everything well but when the "Wrinting video (directory)/rendered.mp4 bar reaches 70% of loading my computer freezes. I have no errors at the time of the freeze.

Do you have any idea where this might come from?

Thanks

**Comment by offish** [comment]
Does your whole computer freeze or is it just the rendering? Do you have to reboot your computer?

**Comment by maxencefiu** [comment]
I just found the source of the problem, my antivirus was blocking the software hehe :)

Great code! Works very well!
I use for this channel :
http://www.youtube.com/channel/UCsLBL5aKrALqlwI5QLdyPPA

Thanks !!!!
