### ISSUE TITLE
Fails to edit video for youtube

### ISSUE THREAD

**Issue by OfficiallySp777** [offish/twitchtube#4]
I decided to test this out with the just chatting Catagory. The twitch clips download fine but afterwards. I get a traceback error
![image](https://user-images.githubusercontent.com/46799448/85810335-a617cb80-b752-11ea-9318-b351f85b14ca.png)

**Comment by OfficiallySp777** [comment]
UPDATE: Reset the config file to default and now i am getting this error after the video has been edited together
![image](https://user-images.githubusercontent.com/46799448/85812588-f3973700-b758-11ea-9317-5b2fa745e494.png)

**Comment by offish** [comment]
Could you show your config.py without CLIENT_ID and OAUTH_TOKEN?

**Comment by OfficiallySp777** [comment]
![image](https://user-images.githubusercontent.com/46799448/86109526-620f2880-babc-11ea-8c32-81cf50dcbc27.png)

**Comment by offish** [comment]
You have not added 'Just Chatting' under TAGS and DESCRIPTIONS so the bot crashes when trying to look for something that doesn't exist. You can simply copy 'Rust' with all it's tags and paste it between 'Rust' and 'Team Fortress 2' and then change the name to 'Just Chatting'. Do the same under descriptions. I will fix the error you've encountered and make the bot upload anyways, but until then just add what I wrote above.
