### ISSUE TITLE
Upload video

### ISSUE THREAD

**Issue by TwitMeet** [offish/twitchtube#40]
I have downloaded twitchtube some time ago and i started getting errors when uploading the video to youtube, so i came here to see if i messed up the code and the upload file is gone.

**Comment by offish** [comment]
Yes, I've changed it to use a package instead. Download the newest version of the repo and install the package by running `pip install --upgrade opplast`. If done correctly, it should upload to YouTube after rendering.

**Comment by TwitMeet** [comment]
oh ok i see thanks :)
by the way whats your youtube channel? (the one where you use twitchtube)

**Comment by offish** [comment]
https://www.youtube.com/channel/UCd0wttXr03lIcTLv38U5d-w but haven't uploaded or used it in a long time, but @Maxencefiu has a channel which is an better example http://www.youtube.com/channel/UCsLBL5aKrALqlwI5QLdyPPA

**Comment by TwitMeet** [comment]
ok thanks again.
