### ISSUE TITLE
Impossible to create more than 50 minutes video

### ISSUE THREAD

**Issue by gantoin** [offish/twitchtube#44]
Hello, I want to do a 3 hours video but I can't. 

I did some tests and I guess it's impossible to do a longer video than around 50 minutes with this params : 

```VIDEO_LENGTH = 60```

More than 60 doesn't work.

**Comment by offish** [comment]
Does it crash/run into any error or is the video just too short? My guess, is that it gets 100 clips, which ads up to be way less than 3 hours and can therefore not add any more clips as it can't find any more.

**Comment by gantoin** [comment]
The video is just too short; you right, I only have 100 clips. The max limit of one API call.
