### ISSUE TITLE
videos are rendering with no sound??

### ISSUE THREAD

**Issue by unniggable** [offish/twitchtube#5]
It downloads all of the clips and then renders into 1 video but the rendered video has no sound (the clips have sound)

**Comment by lxgameshow** [comment]
> It downloads all of the clips and then renders into 1 video but the rendered video has no sound (the clips have sound)

Hello. This program is no longer supported, developer has closed my question.

**Comment by offish** [comment]
You can try to update moviepy and run the bot again, that might fix your issue. Never encountered this before, are you sure your video player is not muted and the video has no sound at all?

**Comment by unniggable** [comment]
> 
> 
> You can try to update moviepy and run the bot again, that might fix your issue. Never encountered this before, are you sure your video player is not muted and the video has no sound at all?

yep it is not muted. I have googled around and a lot of people have had this issue with moviepy but I have not found the solution just yet. I have made it render a temp audio file as well as the video file but i am not sure how to get them both together without having to render it twice :(

**Comment by manu1002** [comment]
@unniggable I have the same issue. Can you tell me how to create a temp audio file aswell?

**Comment by Parapheen** [comment]
That helped me

https://github.com/Zulko/moviepy/issues/876#issuecomment-586410777

**Comment by OfficiallySp777** [comment]
updating moviepy in requirements fixed the issue for me. made a pull request
