### ISSUE TITLE
Title of youtube videos just showing as "asdasda" instead of name of the clip

### ISSUE THREAD

**Issue by arblad1990** [offish/twitchtube#53]
Hey, so i'm pulling 1 clip at a time rather than a compilation, i'm rendering these with my video outro and the file name shows as rendered. When uploading to youtube it always just names it as asdasda, if there any way to make it pull the name of the clip automatically?

Thanks!

**Comment by PepNieto** [comment]
Just let the field of TITLE empty in the config file

**Comment by arblad1990** [comment]
I have, this is what the config file shows:
" TITLE = ""  # youtube title, leave empty for the first clip's title "
But leaving it empty doesn't fill it with the clip's title it just uploads it as ""asdasda" for all of them

**Comment by PepNieto** [comment]
Then maybe the problem is the command ur using for execute the python, are u letting title empty aswell?

if you just execute it like this "python main.py --data "game Just Chatting"
it should put the name of the first clip...

**Comment by arblad1990** [comment]
Thanks that worked! I also worked out why it kept pulling it with that title it's beause the clips name was actually asdasda and it kept uploading the same one over and again lol
