### ISSUE TITLE
please make deploy to heroku button

### ISSUE THREAD

**Issue by raisedhand** [offish/twitchtube#55]
hi offish ,
please if it's possible make deploy to heroku button for free of monthly vps charge. also heroku have any buildpack you need like selenium , chrome headless , ffmpeg or ...
waiting for your response
finest regards

**Comment by offish** [comment]
Sorry, but I won't make this. I have never tried or worked with heroku, but you should be able to deploy it yourself, every needed package is in the requirements. I'm going to add the option to specify the path to geckodriver instead of having to adding it to PATH, if that helps.
