### ISSUE TITLE
schedule the bot for running every day  

### ISSUE THREAD

**Issue by GAMEBEST-GB** [offish/twitchtube#56]
raise VideoPathAlreadyExists("specify another path")
twitchtube.exceptions.VideoPathAlreadyExists: specify another path

**Comment by offish** [comment]
What's the issue?

**Comment by GAMEBEST-GB** [comment]
Thank You For your quick Replaying.
When Scheduling The Script, For Example, I Have Schudel To Run and make video Every 2h, First Running Ends Sucssuley, But When Bot Run Again Ended With EROR ( raise VideoPathAlreadyExists("specify another path") Clips Folder Path.

**Comment by GAMEBEST-GB** [comment]
I Think The Script Dos do not Have The ability To Automatically Remover The Old Sub Folders Created By The Script After Sucsuful Uploading To Youtube  In Clip Folder.

**Comment by offish** [comment]
I see, I'll take a look and figure out a fix.

**Comment by offish** [comment]
I don't really get why this is happening, but I've made a quickfix and the example in the README is updated now.

**Comment by GAMEBEST-GB** [comment]
Thank You So much Frind For The Hope And The Support, I really appreciate
this.

**Comment by GAMEBEST-GB** [comment]
Thank You So much Frind For The Hope And The Support, I really appreciate this.
