### ISSUE TITLE
OAuth Token

### ISSUE THREAD

**Issue by manu1002** [offish/twitchtube#6]
Im sorry if this is a super dumb question but I really dont understand how to get an OAuth token. When I try to use the site you mention (https://twitchapps.com/tokengen/). It wants my Client-ID and something for "scopes". I just dont know what to type in there. The other problem is that I dont know what to fill the client_secret.json with for the most part.
[https://prnt.sc/tnf1pp](url)
[https://prnt.sc/tnf1v4](url)

**Comment by offish** [comment]
You don't actually need to fill out "Scopes", just "Connect" and get your OAuth token.
You're not actually expected to fill out the client secret file, this is a file given to you by the Google Cloud Platform when you've created an OAuth 2.0 Client ID. 
![image](https://user-images.githubusercontent.com/30203217/88332142-64b51480-cd2e-11ea-9c42-90574112b672.png)

For the file that should look like this: 
`"{\"token\": \"example\", \"expiry\": null, \"_scopes\": null, \"_refresh_token\": \"example\", \"_id_token\": null, \"_token_uri\": \"https://oauth2.googleapis.com/token\", \"_client_id\": \"example.apps.googleusercontent.com\", \"_client_secret\": \"example\"}`
I've actually forgot how to get it, but I will update the README when I've figured it out. 
I will also add more information under Setup, as I've received multiple questions about this.

**Comment by manu1002** [comment]
Ah alright but when I press connect i get redirected to these sites 
[https://prnt.sc/tnhgwc](url)
[https://prnt.sc/tnhh9o](url)
Or is there a certain URL I have to use within the OAuth Redirect URLs at dev.twitch.tv/console/apps ? At the moment im using localhost which doesnt look right.

**Comment by offish** [comment]
Go to Twitch Developer Console and set your redirect URL to https://twitchapps.com/tokengen/
Now you can connect and authorize with your Twitch account, and it should hopefully work.
(Deleted your comment as you leaked your Client ID in your first picture)

**Comment by manu1002** [comment]
Oh man god bless you. The second I saw your reply i felt super dumb. In the meantime I got my client secret from google aswell. The only entry thats missing in the file is redirect_uris. Do i need something special for it?

**Comment by offish** [comment]
Try running it without, it might work.

**Comment by manu1002** [comment]
Im sorry for asking so much but the very last thing im missing is the refresh token inside the credentials.json and I really cant find where to get it.

**Comment by offish** [comment]
I will try to figure out how I got it, can't remember at the moment.

**Comment by manu1002** [comment]
Alright hope you find something but still big thanks

**Comment by offish** [comment]
Never mind I'm retarded. Delete the whole credentials folder with the file inside and just run it. It should create the folder and file automatically. Pushing some changes to README now so it will be easier to setup for others.
