### ISSUE TITLE
Only use top clips?

### ISSUE THREAD

**Issue by ricozyx** [offish/twitchtube#70]
Is there anyway in the current Twitchtube release to only use Top clips from the channels you specified or does this already do this and do I have bad settings/too small channels.

**Comment by offish** [comment]
It should only get the most viewed clips by default. What are you getting?

**Comment by ricozyx** [comment]
Got some clip where it was mispositioned (streamer said "clip it" but that's where the clip started lmao).
Though I did try it on a smaller streamer so I assume it might be because their clips had little views.

**Comment by offish** [comment]
Go to the streamer's channel and go to his/her clips and use the same period as you've specified when running. See if the clip is one of the more viewed ones.

**Comment by ricozyx** [comment]
> 
> 
> Go to the streamer's channel and go to his/her clips and use the same period as you've specified when running. See if the clip is one of the more viewed ones.

Yea, seems it got fviews for whatever reason.

Perhaps an enhancement idea would be only use clips with minimum X amount of views.
Would be great in some use cases.

Thanks for open-sourcing this project either way!

**Comment by offish** [comment]
Yeah having a minimum would be great in some cases and terrible in others. Will leave it as it is, but feel free to change it locally.
