### ISSUE TITLE
Exception has occurred: TypeError [When its trying to upload]

### ISSUE THREAD

**Issue by Laezor** [offish/twitchtube#77]
expected str, bytes or os.PathLike object, not int
  File "E:\twitchtube\twitchtube\video.py", line 193, in make_video
    upload = Upload(profile_path, sleep, headless, debug)
  File "E:\twitchtube\twitch clips.py", line 5, in <module>
    make_video(

I do have geckodriver added to the path.

**Comment by zeak6464** [comment]
Make sure geckodriver is running

**Comment by offish** [comment]
You're running the latest version of opplast (v1.0.7), but haven't updated twitchtube.

**Comment by Laezor** [comment]
Updated to the latest version and I have gecko driver running. I got this error now `error: There was an error Message: Unable to locate element: //input[@type='file']
 when trying to upload to YouTube`

**Comment by offish** [comment]
Works fine for me, set `HEADLESS = False` and try again

**Comment by Laezor** [comment]
Works fine now, thank you!
