### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by omsenjalia** [offish/twitchtube#82]
Could this work on mobile terminals such as Termux and UserLAnd

**Comment by offish** [comment]
No clue, try it out

**Comment by omsenjalia** [comment]
Sure, and can you give me **more** detailed thing to see how it works? Like does it auti upload the vids

**Comment by omsenjalia** [comment]
> Sure, and can you give me **more** detailed thing to see how it works? Like does it auti upload the vids

@offish
