### ISSUE TITLE
error while uploading on youtube

### ISSUE THREAD

**Issue by chaitanya1844** [offish/twitchtube#89]
it opens the firefox window and even write a title but dont proceed i have upgraded opplast
i have headless False also my sleep is 120 sec to give video enough time to proceed upload but it gives me this error everytime
error ↓

twitchtube | 06:21:11 - error: There was an error Message: Unable to locate element: /html/body/ytcp-uploads-dialog/tp-yt-paper-dialog/div/ytcp-animatable[1]/ytcp-video-metadata-editor/div/ytcp-video-metadata-editor-basics/div[2]/ytcp-social-suggestions-textbox/ytcp-form-input-container/div[1]/div[2]/div[1]/ytcp-mention-input
 when trying to upload to YouTube
DEBUG: Closed Firefox

**Comment by random-deve** [comment]
Hey, I am receiving this error, would you mind telling me what you did to fix this? Thanks in advance!

**Comment by rywill27** [comment]
Was this ever resolved?
